name: medallion-demo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - pyarrow
      - duckdb
      - sqlalchemy
      - matplotlib
      - pyspark
      - jupyterlab
      - notebook
